# Generated by Django 3.2.3 on 2021-05-13 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_calculator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculation',
            name='creation_date',
        ),
    ]
