# Generated by Django 3.2.3 on 2021-05-13 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_calculator', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calculations',
            new_name='Calculation',
        ),
    ]
