# Generated by Django 3.2.3 on 2021-05-13 21:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('simple_calculator', '0002_rename_calculations_calculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
