# Generated by Django 3.2.3 on 2021-05-13 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_calculator', '0004_testtable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestTable',
        ),
    ]
